### ISSUE TITLE
Error parsing Xauthority file

### ISSUE THREAD

**Issue by spaceotter** [sharplispers/clx#155]
Using:
SBCL 1.5.5
#<SYSTEM clx / clx-20191008-git / quicklisp 2019-10-08>
extra/xorg-server 1.20.5-4.1
extra/xorg-xauth 1.1-1

CLX seems to be having trouble parsing the .Xauthority file:
```
CL-USER> (XLIB::GET-BEST-AUTHORIZATION "" 0 :LOCAL)
```
```
end of file on #<SB-SYS:FD-STREAM for "file /home/eric/.Xauthority" {1001839A83}>
   [Condition of type END-OF-FILE]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1001AC9BC3}>)

Backtrace:
  0: (SB-IMPL::INPUT-UNSIGNED-8BIT-BYTE #<SB-SYS:FD-STREAM for "file /home/eric/.Xauthority" {1001839A83}> T NIL)
  1: (READ-BYTE #<SB-SYS:FD-STREAM for "file /home/eric/.Xauthority" {1001839A83}> T NIL)
  2: ((LABELS XLIB::READ-SHORT-LENGTH-VECTOR :IN XLIB::READ-XAUTH-ENTRY) #<SB-SYS:FD-STREAM for "file /home/eric/.Xauthority" {1001839A83}>)
  3: (XLIB::READ-XAUTH-ENTRY #<SB-SYS:FD-STREAM for "file /home/eric/.Xauthority" {1001839A83}>)
  4: (XLIB::GET-BEST-AUTHORIZATION "" 0 :LOCAL)
```
The file contents: (Edit: see later post)
```
~ $ hexdump .Xauthority
0000000 0001 0b00 7541 7574 6e6d 7543 6562 004c
0000010 3001 1200 494d 2d54 414d 4947 2d43 4f43
0000020 4b4f 4549 312d 1000 27e3 7326 05b9 539c
0000030 5a18 510b 0225 166b 7541 7574 6e6d 7543
0000040 6562 004c 3001 1200 494d 2d54 414d 4947
0000050 2d43 4f43 4b4f 4549 312d 1000 6b71 11f9
0000060 82df fd23 fb6b 9fdd cd84 592a          
000006c
```
The xauth command seems happy with this file though.

**Comment by PuercoPop** [comment]
The problem seems to be that your `.Xauthority` file seems to be in little-endian. afaik it is supposed to by in big-endian. At least the code in CLX and in libXau assume so. 

Strings in the xauthority file are prefixed by their length. In the case of your file due to the mismatch in expected endianess instead of trying to read 11 bytes (`000b`) read-xauth-entry is trying to read 2816 bytes (`0b00`) and reaching the end of file why still trying to read the second field of the first entry.

> The xauth command seems happy with this file though.

You mean it is able to list the the entry? It isn't able to do that on my end. And I doubt that it is able to from reading the source code: https://gitlab.freedesktop.org/xorg/lib/libxau/blob/d9443b2c57b512cfb250b35707378654d86c7dea/AuRead.c#L40

**Comment by spaceotter** [comment]
Sorry for the confusion... I forgot that hexdump reverses the bytes.
```
$ od -t x1 .Xauthority 
0000000 01 00 00 0b 41 75 74 75 6d 6e 43 75 62 65 4c 00
0000020 01 30 00 12 4d 49 54 2d 4d 41 47 49 43 2d 43 4f
0000040 4f 4b 49 45 2d 31 00 10 2d 74 f5 8b b5 c6 68 1d
0000060 cf 4f f4 be c7 c1 ab a6 41 75 74 75 6d 6e 43 75
0000100 62 65 4c 00 01 30 00 12 4d 49 54 2d 4d 41 47 49
0000120 43 2d 43 4f 4f 4b 49 45 2d 31 00 10 71 6b f9 11
0000140 df 82 23 fd 6b fb dd 9f 84 cd 2a 59
0000154
```

**Comment by PuercoPop** [comment]
I can't reproduce on my end. clx can parse that file just fine

```lisp
(with-open-file (in #P"/home/puercopop/quicklisp/local-projects/attic/random-xauth"
                    :element-type '(unsigned-byte 8))
  (xlib::read-xauth-entry in))
;; =>
(:LOCAL "AutumnCubeL" 0 "MIT-MAGIC-COOKIE-1"
 #(45 116 245 139 181 198 104 29 207 79 244 190 199 193 171 166))
```

**Comment by spaceotter** [comment]
Your code works for me too. It's the call `(XLIB::GET-BEST-AUTHORIZATION "" 0 :LOCAL)` that fails. This is in the backtrace when trying to run the mcclim demos.
get-best-authorization calls read-xauth-entry in a loop, its seems that the second call needs to return (nil ...) in order to break out of the loop, but it throws an error instead. Try calling read-xauth-entry twice on the stream in your example.

**Comment by PuercoPop** [comment]
> its seems that the second call needs to return (nil ...)

It is the third call that should return (nil ...) as your file has two entries. You can see that it has two entries because AutumnCubeL and MIT-MAGIC-COOKIE-1 appear twice in your file.

The problem is that the second entry is malformed, it is missing the first 4 bytes. The payload of the mit cookie which goes from the `0010` in the third line (which is the length of the payload, so 16 bytes) to the `ABA6` of the fourth line and then it jumps directly to AutumCube. The second entry is missing both the family and the length of the address. So it interprets the `tu` (#x7475, 29813) as the length of your hostname and goes overboard. 

Note that the xauth can't parse can't parse your whole file correctly either as it lists one entry only and fails silently on the second one.

If we patch your file to add the 4 missing bytes, 0000, which means internet/tcp and 00B0, which is the length of your hostname, calling `(XLIB::GET-BEST-AUTHORIZATION "" 0 :LOCAL)` works as expected.

It is common for `.Xauthority` to have two entries at least, one for when dealing with unix socket and one for when dealing with TCP sockets. They usually have the same value for the MIT-MAGIC-COOKIE-1. That is not the case in the patched version of your file which leads me to suspect that it might be a left over from the file being overwritten and that your hostname previously was shorter by 4 characters and that you've now disabled connecting to your XServer through tcp.

idk if it is a good idea to fail silently upon running into malformed entries, but I'll leave that call up to the maintainers of CLX. You should be able to fix the issue by deleting the file and starting your XServer again.

```
$ od -t x1 random-xauth-patched
0000000 01 00 00 0b 41 75 74 75 6d 6e 43 75 62 65 4c 00
0000020 01 30 00 12 4d 49 54 2d 4d 41 47 49 43 2d 43 4f
0000040 4f 4b 49 45 2d 31 00 10 2d 74 f5 8b b5 c6 68 1d
0000060 cf 4f f4 be c7 c1 ab a6 00 00 00 0b 41 75 74 75
0000100 6d 6e 43 75 62 65 4c 00 01 30 00 12 4d 49 54 2d
0000120 4d 41 47 49 43 2d 43 4f 4f 4b 49 45 2d 31 00 10
0000140 71 6b f9 11 df 82 23 fd 6b fb dd 9f 84 cd 2a 59
0000160
```

And the code to write it
```lisp
(let ((file-contents #(1 0 0 11 65 117 116 117 109 110 67 117 98 101 76 0 1 48 0 18 77 73 84 45 77 65 71 73 67 45 67 79 79 75 73 69 45 49 0 16 45 116 245 139 181 198 104 29 207 79 244 190 199 193 171 166 0 0 0 11 65 117 116 117 109 110 67 117 98 101 76 0 1 48 0 18 77 73 84 45 77 65 71 73 67 45 67 79 79 75 73 69 45 49 0 16 113 107 249 17 223 130 35 253 107 251 221 159 132 205 42 89)))
  (with-open-file (out #P"foo-xauth"
                       :direction :output
                       :element-type '(unsigned-byte 8)
                       :if-does-not-exist :create)
    (loop :for byte :across file-contents
          :do (write-byte byte out))))
```

**Comment by spaceotter** [comment]
You're right, I did change the hostname of the machine.
Nuking .Xauthority and restarting resolves the issue (clim demo works normally).
Thanks a lot for the help!
