### ISSUE TITLE
clx: display-keyboard-mappings: spurious caching of the mappings

### ISSUE THREAD

**Issue by dkochmanski** [sharplispers/clx#53]
Steps to reproduce:
1. Set keyboard layout to English before starting lisp
   `setxkbmap -layout us`
2. Start any application using clx (for instance climacs)

``` common-lisp
(eval-when (:load-toplevel :compile-toplevel :execute)
  (ql:quickload 'climacs))
(climacs:climacs)
```
1. Type a few characters in climacs (layout is qwerty)
2. Change layout from the console
   `setxkbmap -layout fr`
3. Type a few more characters in climacs (layout is still qwerty)

How to fix:

``` diff
diff --git a/translate.lisp b/translate.lisp
index 0b0d7a8..64bc183 100644
--- a/translate.lisp
+++ b/translate.lisp
@@ -279,8 +279,7 @@
 (defun display-keyboard-mapping (display)
   (declare (type display display))
   (declare (clx-values (simple-array keysym (display-max-keycode keysyms-per-keycode))))
-  (or (display-keysym-mapping display)
-      (setf (display-keysym-mapping display) (keyboard-mapping display))))
+  (setf (display-keysym-mapping display) (keyboard-mapping display)))

 (defun keycode->keysym (display keycode keysym-index)
   (declare (type display display)
```

Fix proposed in: https://github.com/robert-strandh/McCLIM/issues/35

**Comment by PuercoPop** [comment]
I've been thinking about what would be the ideal solution, CLX would provide two classes for display, the vanilla and the cached-keysyms-display. The user of CLX could decide with which version to start the connection. However due to CLX's design, that favors minimizing the round trips doing this would require heavy modifications to the code base. A more workable solution would be to document the problem in the manual and provide example code of how to handle the keyboard layout changing notify-event in the client code.

Thoughts?

**Comment by dkochmanski** [comment]
This is correct behavior, McCLIM handles it correctly and stumpwm does as well. See closed wip fix (last comment) for explanation, why we don't want to handle this in clx (https://github.com/sharplispers/clx/pull/54).
